# Generated by Django 3.1.5 on 2021-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_auto_20210130_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='andar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='valor_aluguel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='valor_venda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
