# Generated by Django 3.1.5 on 2021-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_imoveis_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
