# Generated by Django 3.1.5 on 2021-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('tipo_negocio', models.CharField(max_length=20)),
                ('tipo_imovel', models.CharField(max_length=25)),
                ('valor_aluguel', models.IntegerField()),
                ('valor_venda', models.IntegerField()),
                ('valor_iptu', models.IntegerField()),
                ('valor_condominio', models.IntegerField()),
                ('area', models.IntegerField()),
                ('quartos', models.IntegerField()),
                ('suites', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('vagas', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('metro_proximo', models.BooleanField()),
                ('descricao', models.TextField(max_length=1000)),
                ('publicado', models.BooleanField()),
            ],
        ),
    ]
