# Generated by Django 3.1.5 on 2021-01-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoveis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imoveis')),
            ],
        ),
    ]
