# Generated by Django 3.1.5 on 2021-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_auto_20210130_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='mobiliado',
            field=models.BooleanField(default=False),
        ),
    ]
